version: "3.3"

services:
  solvent:
    image: solvent:latest
    volumes:
      - "./conf:/app/web/conf:ro"
      - "./secrets:/app/web/secrets:ro"
    ports:
      - 5000:8080
    restart: always

  db:
    image: postgres
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_USER: solvent
      POSTGRES_PASSWORD: solvent123

