version: "3.3"
services:
  solvent:
    image: solvent:latest
    ports:
      - 5000:8080
    restart: always

  db:
    image: postgres
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_USER: solvent
      POSTGRES_PASSWORD: solvent123

