version: "3.3"

services:
  solvent:
    image: solvent:latest
    volumes:
      - "./conf:/app/web/conf:ro"
      - "./secrets:/app/web/secrets:ro"
    ports:
      - 5000:8080
    restart: always

  db:
    image: postgres
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    secrets:
      - postgres-user
      - postgres-password

secrets:
  postgres-user:
    file: ./secrets/postgres-user.txt
  postgres-password:
    file: ./secrets/postgres-password.txt
