version: "3.5"

services:
  solvent:
    image: solvent:latest
    volumes:
      - "./conf:/app/web/conf:ro"
      - "./secrets:/app/web/secrets:ro"
    networks:
      - solvent_net
      - caddy_net
    expose:
      - 8080
    restart: always

  db:
    image: postgres
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    networks:
      - solvent_net
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    secrets:
      - postgres-user
      - postgres-password

secrets:
  postgres-user:
    file: ./secrets/postgres-user.txt
  postgres-password:
    file: ./secrets/postgres-password.txt

networks:
  solvent_net:
  caddy_net:
    name: caddy_net
    external: true
